### PR TITLE
Highlight improvements

### PR DESCRIPTION
**Pull request by aspeddro**
1. Extension points: `%raw`, `%%raw`, `%re`
2. Top level Attribute: `@@attribute`
3. Highlight `list` in `list{...}` as `Function`
4. Highlight `[`, `]`, `(`, `)` `{` and `}`
5. Link `open` and `include` to `Include`
6. Link `try` `catch` `exception` `assert` to `Exception`
7. Link `for` `to` `downto` `while` to `Repeat`
8. Add `promise` type
9. Move `|` to `resDelimiter` group.

#68

### CODE REVIEW

**Comment by ryyppy** [comment]
Can you add some quick example in some of the test fixture files (or a new separate test fixture file), so it's easy to visually verify the change locally?

**Comment by aspeddro** [comment]
I changed `in` to `Repeat` group

**Comment by aspeddro** [comment]
Added support to custom operators `\"op"`

image

image

**Comment by ryyppy** [comment]
lgtm. Feel free to merge (you should have write credentials by now).

**Pull request merged**
