### PR TITLE
Fix highlighting for nested multiline comments

### LINKED ISSUE #21: Syntax highlighting for nested /* */ broken
Currently this doesn't highlight correctly:

```
/*

/* This function does something*/
let someCode () => {
  ()
}
*/
```

The inner comment breaks the highlighting

### PR DESCRIPTION
**Pull request by amiralies**
Closes #21

### CODE REVIEW

**Comment by amiralies** [comment]
This is a quick fix. I didn't find any major mis-highlighting. Can you give it a try @ryyppy ?
I think we can improve this when we introduced rescript's doc comments

**Comment by ryyppy** [comment]
yeah i will try it. Thanks for proposing the change!

**Comment by ryyppy** [comment]
Seems like there is an edge-case when using `//` within `/**/` in the same line:

image

**Comment by amiralies** [comment]
Fixed!

**Comment by ryyppy** [comment]
Looking good so far (have been using it for quite a while now). I will extend my usage for a few more days just to be sure that everything is working correctly.

**Comment by ryyppy** [comment]
had a fair share testing this, I am fine getting this merged with an appropriate Changelog update

**Review by ryyppy — APPROVED** [review]
had a fair share testing this, I am fine getting this merged with an appropriate Changelog update

**Pull request merged**
