### PR TITLE
Fix syntax highlighting synchronization

### LINKED ISSUE #14: Highlighting bug when having template string literals
I experience some issues with syntax highlighting whenever I browse some bigger template string codeblocks, mixed with normal ReScript code:

```rescript
%%bs.raw(
  `
function PromiseBox(p) {
    this.nested = p;
};
function unbox(value) {
    if (value instanceof PromiseBox)
        return value.nested;
    else
        return value;
}
function box(value) {
    if (value != null && typeof value.then === 'function')
        return new PromiseBox(value);
    else
        return value;
}
function make(executor) {
    return new Promise(function (resolve, reject) {
        var boxingResolve = function(value) {
            resolve(box(value));
        };
        executor(boxingResolve, reject);
    });
};
function resolved(value) {
    return Promise.resolve(box(value));
};
function then(promise, callback) {
    return promise.then(function (value) {
        try {
            return callback(unbox(value));
        }
        catch (exception) {
            onUnhandledException.contents(exception);
        }
    });
};
function catch_(promise, callback) {
    var safeCallback = function (error) {
        try {
            return callback(error);
        }
        catch (exception) {
            onUnhandledException.contents(exception);
        }
    };
    return promise.catch(safeCallback);
};
`
)

type result<'a, 'e> = Belt.Result.t<'a, 'e> = Ok('a) | Error('e)

module Js_ = {
  type t<'a, 'e> = rejectable<'a, 'e>

  external relax: promise<'a> => rejectable<'a, _> = "%identity"

  @bs.val
  external jsNew: (('a => unit, 'e => unit) => unit) => rejectable<'a, 'e> = "make"

  let pending = () => {
    let resolve = ref(ignore)
    let reject = ref(ignore)
    let p = jsNew((resolve', reject') => {
      resolve := resolve'
      reject := reject'
    })
    (p, resolve.contents, reject.contents)
  }

  @bs.val
  external resolved: 'a => rejectable<'a, _> = "resolved"

  @bs.val
  external flatMap: (rejectable<'a, 'e>, 'a => rejectable<'b, 'e>) => rejectable<'b, 'e> = "then"

  let map = (promise, callback) => flatMap(promise, v => resolved(callback(v)))

  let get = (promise, callback) => ignore(map(promise, callback))

  let tap = (promise, callback) => {
    get(promise, callback)
    promise
  }

  @bs.scope("Promise") @bs.val
  external rejected: 'e => rejectable<_, 'e> = "reject"

  @bs.val
  external catch: (rejectable<'a, 'e>, 'e => rejectable<'a, 'e2>) => rejectable<'a, 'e2> = "catch_"

  @bs.val
  external unbox: 'a => 'a = "unbox"

  @bs.scope("Promise") @bs.val
  external jsAll: 'a => 'b = "all"

  let allArray = promises => map(jsAll(promises), promises => Belt.Array.map(promises, unbox))

  let all = promises => map(allArray(Belt.List.toArray(promises)), Belt.List.fromArray)

  let all2 = (p1, p2) => jsAll((p1, p2))

  let all3 = (p1, p2, p3) => jsAll((p1, p2, p3))

  let all4 = (p1, p2, p3, p4) => jsAll((p1, p2, p3, p4))

  let all5 = (p1, p2, p3, p4, p5) => jsAll((p1, p2, p3, p4, p5))

  let all6 = (p1, p2, p3, p4, p5, p6) => jsAll((p1, p2, p3, p4, p5, p6))

  @bs.scope("Promise") @bs.val
  external jsRace: array<rejectable<'a, 'e>> => rejectable<'a, 'e> = "race"

  let race = promises =>
    if promises == list{} {
      raise(Invalid_argument("Promise.race([]) would be pending forever"))
    } else {
      jsRace(Belt.List.toArray(promises))
    }

  let toResult = promise => catch(map(promise, v => Ok(v)), e => resolved(Error(e)))

  let fromResult = promise => flatMap(relax(promise), x =>
      switch x {
      | Ok(v) => resolved(v)
      | Error(e) => rejected(e)
      }
    )

  external fromJsPromise: Js.Promise.t<'a> => rejectable<'a, Js.Promise.error> = "%identity"

  external toJsPromise: rejectable<'a, _> => Js.Promise.t<'a> = "%identity"
}

```

As soon as I navigate to the beginning of the `Js_` module, the highlighting bugs out and marks all the rest of my current view buffer as a string:

image

Notice how the content of the template string gets highlighted as regular ReScript code, while the code outside of the template string is highlighted as a string.

This behavior is sometimes hard to reproduce. Sometimes i just `j,h,k,l` navigate to a point where this behavior gets triggered, sometimes the reformatter triggers a rerender of the syntax highlighting.

Oftentimes  `:e!` or inserting a line in the current code position temporarily fixes the problem. It's really annoying though.

### PR DESCRIPTION
**Pull request by amiralies**
Closes #14

### CODE REVIEW

**Comment by amiralies** [comment]
according to vim docs (`:h :syn-sync-first`),
`syntax sync fromstart` is equivalent to using a large value for minlines.
This is what vim-javascript [uses](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L22).
I think this solves sync issue for all cases, maybe wen can go with this for now and if we faces performance issues we can use an optiomal value for min / max value

**Comment by ryyppy** [comment]
I tend to have enormous ReScript files (just check the [`re_pages/Playground.res`](https://github.com/reason-association/rescript-lang.org/blob/master/re_pages/Playground.res) file, that spans more than 1500 lines), I'd rather would like to try a line number of 600 or so

I think JavaScript workflows are different, because they tend to create a hundred 10 line files, instead of one 1000 line file

**Comment by amiralies** [comment]
You're right, long js files are headache but it's so natural to have large files in a language with ml style typesystem like ReScript.
IMO I don't think if it causes major performance issues but yeah we like vim because it's FAST. so for now we go with 600 and if we had problems (either large multiline strings or large comments) with this we can tweak the number or use sync fromstart.

**Comment by ryyppy** [comment]
Yeah let's keep an eye on that. I think 600 will be fine, just don't want to stress vim too much early on

thanks!

**Pull request merged**
