### PR TITLE
Fixes #17 - Support for Monorepos using Yarn Workspaces

### LINKED ISSUE #17: Support for Monorepos via Yarn Workspaces
Looks like the format will not work since the binary is only stored top level in the project under the global node_modules directory.

I understand this is a bit tricky or odd since each sub module can use a different version of bs-platform, but I am wondering if there is a way to traverse up until the node_modules/bs-platform is found, and at the point, use the latest version?

### PR DESCRIPTION
**Pull request by danwetherald**
I took a look how the path is defined when sourcing the binaries and this seems to keep looking up until the `node_modules` directory is found that also includes a `bs-platform` directory.

Let me know if anyone sees any issues with this, I tried this both on a monorepo project and a traditional project and it seems to work for both projects.

### CODE REVIEW

**Comment by ryyppy** [comment]
interesting, will need to try that. do you have any public yarn workspaces / rescript repo where I can test this myself?

**Comment by danwetherald** [comment]
I do not have any public repos using yarn workspaces, but I can certainly create an example repo if need be. 

Let me know if that is something you would like me to do for testing purposes.

**Comment by ryyppy** [comment]
yeah, maybe create an examples/monorepo folder within this PR so we can keep it around for integration testing later on?

**Comment by danwetherald** [comment]
Just pushed up a quick and simple example for a monorepo @ryyppy - Let me know if this helps.

`$ cd examples/monorepo`

`$ yarn install` (this is done in the root dir

`$ cd awesomeness`
`$ yarn re:clean && yarn re:watch`

`$ cd app`
`$ yarn re:clean && yarn re:watch`
`$ yarn start`

**Comment by ryyppy** [comment]
Thanks.

I needed to simplify your example and add some other stuff, so I will close this PR in favour of #19

**Comment by danwetherald** [comment]
> Thanks.
> 
> I needed to simplify your example and add some other stuff, so I will close this PR in favour of #19

Sounds good.

**Comment by ryyppy** [comment]
@dan003400 We still need to coordinate with Bob if this is the correct way to detect tooling from a compiler perspective. For now we will keep the aforementioned PR (#19) in a draft state.

Closing this PR.

**Pull request closed without merging**
