### PR TITLE
Add syntax highlighting support for int polyvars

### PR DESCRIPTION
**Pull request by amiralies**

### CODE REVIEW

**Comment by ryyppy** [comment]
sorry for the delay, I guess we can safely assume that this will just work as advertised? How does the new syntax look like in a screenshot?

**Comment by amiralies** [comment]
Looks similar to other polyvar syntaxes.
image

Should we update this based on this commit https://github.com/rescript-lang/syntax/commit/dc533708f1f5c45eb5c7095b9d01175f81955883 to disallow higlighting of `#10abc`?

**Comment by ryyppy** [comment]
> Should we update this based on this commit rescript-lang/syntax@dc53370 to disallow higlighting of #10abc?

Yeah that would be neat.

Can you also create a new file in the [basic example folder](https://github.com/rescript-lang/vim-rescript/tree/master/examples/basic/src) called `polySyntax.res` and add some different polyvar assignments? 

This might be useful to later on look through all the different syntax highlighting features.

(Definitely need to get rid of the `bar.res`, `baz.res` wording at some point..)

**Comment by ryyppy** [comment]
looking good now! feel free to merge when this is ready 👍

**Pull request merged**
