### PR TITLE
Patch 2.0.1

### PR DESCRIPTION
**Pull request by ryyppy**
For testing:

**vimrc:**

```viml
Plug 'rescript-lang/vim-rescript', {'branch': 'patch-2-0-1'}
```

### CODE REVIEW

**Comment by alexeygolev** [comment]
@ryyppy Ok, this was tough due to a combination of ignores and version mismatches.
You are vendoring a version of `vscode-languageserver-protocol` that depends on [v6.0.0](https://github.com/rescript-lang/vim-rescript/blob/master/server/node_modules/vscode-languageserver-protocol/package.json#L21) of `vscode-jsonrpc`. The version of `vscode-jsonrpc` you're vendoring is [v5.0.1](https://github.com/rescript-lang/vim-rescript/blob/master/server/node_modules/vscode-jsonrpc/package.json#L4) and it doesn't have `/node` that `vscode-languageserver-protocol` requires. The 6.0.0 does.

It works for me when I do `npm install` inside `/server` because a `node_modules` is created inside `vscode-languageserver-protocol` with the 6.0.0 version of `vscode-jsonrpc`. And I couldn't figure out why does it work while there are no visible git changes. `npm install --verbose` helped to see `vscode-jsonrpc` being installed into `node_modules` dir ignored by git:)

**Comment by chenglou** [comment]
Yeah this is fixed in rescript-vscode master

**Comment by ryyppy** [comment]
@alexeygolev yeah it seems my `.gitignore` might have been the problem.
Can you pull from this branch and try again?

**Comment by joakin** [comment]
I've tried this too, on Ubuntu, at this commit: vim-rescript (patch-2-0-1=) → c4e2c25

Rescript commands work well, and my in progress vim-ale integration works now! (using lsp with stdio).

It is the first time I've gotten autocomplete and linting in the editor, and it is magic. Thanks for working on the editor plugins!

I'll share the vim-ale integration in the forum after this PR is merged, and open an issue here to discuss if vim-ale integration is worth having in this repo and documenting in the README.

**Comment by ryyppy** [comment]
@joakin thanks for testing. I will consider this as fixed now and cut a new release 2.0.1.

**Pull request merged**
